# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring.thymeleaf.cache=false
spring.main.show-banner=false
logging.level.jdbc=OFF
logging.level.jdbc.sqltiming=DEBUG
logging.level.jdbc.resultsettable=DEBUG

# Server
server.port=8080

# Snowflake JDBC
spring.datasource.driver-class-name=net.snowflake.client.jdbc.SnowflakeDriver


# Format:
# jdbc:snowflake://<account_identifier>.snowflakecomputing.com/?warehouse=...&db=...&schema=...&role=...
spring.datasource.url=jdbc:snowflake://hnvdtbt-fzc49031.snowflakecomputing.com/?warehouse=ADAPTAMAP_WH&db=ADAPTAMAP_DB&schema=PUBLIC

spring.datasource.username=jswan
spring.datasource.password=Photosynthesis1!@