-- 1) Warehouse (compute)
CREATE OR REPLACE WAREHOUSE ADAPTAMAP_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- 2) Database + schema
CREATE OR REPLACE DATABASE ADAPTAMAP_DB;
CREATE OR REPLACE SCHEMA ADAPTAMAP_DB.PUBLIC;

USE WAREHOUSE ADAPTAMAP_WH;
USE DATABASE ADAPTAMAP_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE NODES (
  NODE_ID            STRING        NOT NULL,
  LAT                NUMBER(9,6)    NOT NULL,
  LON                NUMBER(9,6)    NOT NULL,
  GEOM               GEOGRAPHY      NOT NULL,
  BUILDING_ID        STRING         NULL,
  FLOOR              STRING         NULL,
  METADATA           VARIANT        NULL,
  CREATED_AT         TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT         TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_NODES PRIMARY KEY (NODE_ID)
);

CREATE OR REPLACE TABLE EDGES (
  EDGE_ID            STRING        NOT NULL,
  FROM_NODE_ID       STRING        NOT NULL,
  TO_NODE_ID         STRING        NOT NULL,
  DISTANCE_M         NUMBER(10,2)  NOT NULL,
  EDGE_TYPE          STRING        NOT NULL,
  IS_ACCESSIBLE      BOOLEAN       DEFAULT TRUE,
  SLOPE              NUMBER(5,4)   NULL,
  WIDTH_M            NUMBER(6,2)   NULL,
  SURFACE            STRING        NULL,
  IS_INDOOR          BOOLEAN       DEFAULT FALSE,
  METADATA           VARIANT       NULL,
  CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_EDGES PRIMARY KEY (EDGE_ID)
);

CREATE OR REPLACE TABLE FEATURES (
  FEATURE_ID         STRING        NOT NULL,
  NODE_ID            STRING        NULL,
  EDGE_ID            STRING        NULL,
  FEATURE_TYPE       STRING        NOT NULL,
  STATUS             STRING        NOT NULL,
  DETAILS            VARIANT       NULL,
  START_AT           TIMESTAMP_NTZ NULL,
  END_AT             TIMESTAMP_NTZ NULL,
  CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_FEATURES PRIMARY KEY (FEATURE_ID)
);

CREATE OR REPLACE TABLE PINS (
  PIN_ID             STRING        NOT NULL,
  USER_ID            STRING        NULL,
  LAT                NUMBER(9,6)    NOT NULL,
  LON                NUMBER(9,6)    NOT NULL,
  GEOM               GEOGRAPHY      NOT NULL,
  PIN_TYPE           STRING         NOT NULL,
  DESCRIPTION        STRING         NULL,
  STATUS             STRING         DEFAULT 'PENDING',
  CONFIDENCE         NUMBER(3,2)    DEFAULT 0.50,
  SEVERITY           NUMBER(3,2)    DEFAULT 0.50,
  START_AT           TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
  EXPIRES_AT         TIMESTAMP_NTZ  NULL,
  METADATA           VARIANT        NULL,
  CREATED_AT         TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT         TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_PINS PRIMARY KEY (PIN_ID)
);

ALTER TABLE NODES CLUSTER BY (BUILDING_ID, FLOOR);
ALTER TABLE PINS  CLUSTER BY (STATUS, EXPIRES_AT);

-- sample nodes (Snowflake-safe)
INSERT INTO NODES (NODE_ID, LAT, LON, GEOM, BUILDING_ID, FLOOR)
SELECT 'N1', 38.980000, -76.480000, TO_GEOGRAPHY('POINT(-76.480000 38.980000)'), 'B1', '1'
UNION ALL
SELECT 'N2', 38.980200, -76.480100, TO_GEOGRAPHY('POINT(-76.480100 38.980200)'), 'B1', '1'
UNION ALL
SELECT 'N3', 38.980350, -76.480120, TO_GEOGRAPHY('POINT(-76.480120 38.980350)'), 'B1', '2';

-- sample edges (VALUES is fine here)
INSERT INTO EDGES (EDGE_ID, FROM_NODE_ID, TO_NODE_ID, DISTANCE_M, EDGE_TYPE, IS_ACCESSIBLE, SLOPE, IS_INDOOR)
VALUES
('E1', 'N1', 'N2', 25.0, 'HALLWAY', TRUE, NULL, TRUE),
('E2', 'N2', 'N3', 10.0, 'STAIRS',  FALSE, NULL, TRUE);

-- sample feature (Snowflake-safe)
INSERT INTO FEATURES (FEATURE_ID, NODE_ID, FEATURE_TYPE, STATUS, DETAILS)
SELECT 'F1', 'N2', 'ELEVATOR', 'WORKING', PARSE_JSON('{"servesFloors":["1","2"]}');

-- sample pin (Snowflake-safe)
INSERT INTO PINS (PIN_ID, USER_ID, LAT, LON, GEOM, PIN_TYPE, DESCRIPTION, STATUS, CONFIDENCE, EXPIRES_AT)
SELECT
  'P1', 'U1', 38.980200, -76.480100,
  TO_GEOGRAPHY('POINT(-76.480100 38.980200)'),
  'ELEVATOR_OUT', 'Elevator not working as of today',
  'PENDING', 0.60, DATEADD(day, 2, CURRENT_TIMESTAMP());

-- sanity checks
SELECT * FROM NODES;
SELECT * FROM EDGES;
SELECT * FROM FEATURES;
SELECT * FROM PINS;